# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSX6Zjff-BsfNFbwLxfZQYSNSR5B8lK0
"""

import datetime

study_data = []

def add_session():
    subject = input("Enter subject studied: ")
    duration = int(input("Duration (minutes): "))
    today = datetime.date.today().strftime("%Y-%m-%d")
    study_data.append({"date": today, "subject": subject, "duration": duration})
    print("Session added!\n")

def show_summary():
    if not study_data:
        print("No study sessions recorded yet.\n")
        return

    total_time = sum(s["duration"] for s in study_data)
    avg_time = total_time / len(study_data)

    # Find most productive day
    day_totals = {}
    for s in study_data:
        day_totals[s["date"]] = day_totals.get(s["date"], 0) + s["duration"]
    best_day = max(day_totals, key=day_totals.get)

    print("\n----- STUDY SUMMARY -----")
    print(f"Total study time: {total_time} minutes")
    print(f"Average session duration: {avg_time:.2f} minutes")
    print(f"Most productive day: {best_day} ({day_totals[best_day]} mins)")

    # Consistency score (simple)
    unique_days = len(day_totals)
    consistency = (unique_days / max(1, (len(study_data)))) * 100
    print(f"Consistency score: {consistency:.2f}%")

    # Recommendations
    print("\n--- Recommendations ---")
    if consistency < 50:
        print("Try to study a bit every day even if it's short.")
    if avg_time < 30:
        print("Your sessions are short. Try increasing duration gradually.")
    if day_totals[best_day] > 120:
        print("Great! You had a long productive day. Try to repeat this weekly.")
    print()

def main():
    while True:
        print("1. Add study session")
        print("2. Show summary")
        print("3. Exit")
        choice = input("Enter choice: ")

        if choice == "1":
            add_session()
        elif choice == "2":
            show_summary()
        elif choice == "3":
            print("Goodbye!")
            break
        else:
            print("Invalid choice.\n")

main()